src/main/thrift/atoms/quiz.thrift

I've kept the old `published` boolean in there to maintain backwards compatibility as suggested [here](https://diwakergupta.github.io/thrift-missing-guide/#_versioning_compatibility).
The new field is required for tooling to be able to tell if there are unpublished changes to a quiz content-atom.

Add optional publishedAt field to Quiz thrift definition

---

.gitignore
src/main/thrift/atoms/viewpoints.thrift
src/main/thrift/contentatom.thrift

The thrift model for the viewpoint atom. Feel free to comment and suggest changes.
I've not cut the release binaries yet, I'm using a locally published version to start with (and to get familiar with the model). Once I feel the model is good and I've got a :+1: I'll merge and perform the release.
Is there anything else I need to do (apart from setting up the kinesis stream) to free up the CAPI work.

viewpoint atom

---

build.sbt

This creates a new deliverable which contains just the thrift data, so that we can bring it in as a deliverable and generate it's own thrift based on it, rather than having to replicate it.

Thrift source deliverable

---

build.sbt
doc/new-content-atom.md

This means that you can now publish all of the deliverables from the different projects by doing a `+publishSigned` (or a `+release` etc) from the root project, instead of publishing each individual project individually.

Make root project an aggregation of the other projects

---

build.sbt

Does not prefix artefact with scala and include the thrift file in the jar.

Follow standard way of packaging

---

src/main/thrift/contentatom.thrift

We need to add some additional information to rendering platforms so I am proposing we add two new sets of metadata.

Atom: add optional fields for metadata and flags

---

doc/new-content-atom.md
src/main/thrift/atoms/quiz.thrift

An answer can contribute to a result bucket so each answer can have a list of associated result buckets.

Quizzes: add buckets to answers

---

thrift/src/main/thrift/atoms/media.thrift
thrift/src/main/thrift/contentatom.thrift

We have named this a media atom, to allow for support for audio in the future, but for now it is focussing on video.
It is essentially just a container for pointers to off-platform assets.
The ID, at least in the beginning, will likely map 1-to-1 to a PlutoID but that would be business logic that is enforced outside of the atom model (i.e. at the source of the atom events).
The assets are versioned to allow for the situation where the content has been updated but the latest version of the video has not yet been sent to all of the available platforms.

Media atom model

---

.gitignore
package.json
thrift/src/main/thrift/atoms/media.thrift

We've added:
* title - To make sure the video is at least searchable
* category: There was an editorial decision to make these types of videos, so if we are going to add one, it would have to be well thought out
* duration and source: these will be required for publishing, but as we might not have an asset, duration is optional, and source doesn't need to know at first
This will get us a lot closer to getting one of these into prod.

flesh out media atom to be usable

---

package.json
thrift/src/main/thrift/atoms/media.thrift
version.sbt

If we don't have assets, we won't be able to have an activeVersion.
It was either this or to use `0` or `null` which always feels rubbish.
@akash1810 @paulmr

make activeVersion optional

---

thrift/src/main/thrift/atoms/media.thrift

Not 100% sure why we went with a double if it's in milliseconds.
@akash1810 @paulmr

Make media duration an integer.

---

thrift/src/main/thrift/atoms/media.thrift

So we can get all the URL assets for a particular version of a media atom and render them together in an html `video` block, for example.
/cc @paulmr

Give media-atom assets an optional mime-type

---

thrift/src/main/thrift/atoms/media.thrift

I think this is the last property we need for hosted videos.
/cc @guardian/labs-beta

Add optional poster URL to media atom

---

thrift/src/main/thrift/atoms/explainer.thrift
thrift/src/main/thrift/shared.thrift

This change adds the `Taxonomy` field to a `ExplainerAtom` in the thrift
definition. (Copied over from the existing `Taxonomy` definition presents
in flexible contents.)

ExplainerAtom definition update

---

thrift/src/main/thrift/atoms/cta.thrift
thrift/src/main/thrift/atoms/explainer.thrift
thrift/src/main/thrift/atoms/interactive.thrift
thrift/src/main/thrift/atoms/media.thrift
thrift/src/main/thrift/atoms/quiz.thrift
thrift/src/main/thrift/contentatom.thrift
thrift/src/main/thrift/shared.thrift

This cleans up the following:
- spacing
- explicitly defining enum ordering (makes it much clearer that ordering is important preventing mistakes compromising backwards compatibility when deprecating a value).
- Fixes interactive atom namespace.
- Removes unnecessary comments
- Removes unnecessary semi-colons.
- Corrects illogical ordering of fields.
Whomever reviews this, please check carefully.

Content atom - thrift definitions are a mess - tidy up.

---

js/main.js
package.json

The js/main.js file is missing quite a lot of the content atoms that should be there while the js library is languishing quite far behind at 2.1.1 compared to the 2.4.7 we're currently on. I've updated the version to 2.4.7 to bring in line rather than bumping from what it was previously on. Please shout if you'd prefer I did not do this.

Content Atom - ensure js/main.js is up to date.

---

thrift/src/main/thrift/atoms/media.thrift
thrift/src/main/thrift/contentatom.thrift

Enum values by default start from `0`
The event type mismatch is scary.

Enum should start at 0 for compatibility reasons

---

package.json
thrift/src/main/thrift/atoms/media.thrift
thrift/src/main/thrift/shared.thrift

Update thrift definition for poster image for media atoms. Provides more information about the image than just a URL. Subset of the image data from grid.

Add poster image for media atoms.

---

thrift/src/main/thrift/atoms/media.thrift
thrift/src/main/thrift/contentatom.thrift

Add the same flags for atoms as seen in composer for content:
- ~~Sensitive~~
- Legally Sensitive
- ~~Suppress related content~~
- ~~blockAds~~
There will need to be a discussion around how flags at an atom level interact with the same flags at a content level and which flag 'wins'
EDIT: Follow up discussion - only legally sensitive will be included

Add content flags

---

thrift/src/main/thrift/contentatom.thrift

The suppressFurniture field was added to the model as part of an intended feature but it never got implemented. I've double checked and we have no atoms in Elasticsearch with this field. This also breaks our concept of having fields on our data which make little sense and relate to a UI.
I've confirmed all of this with @clloyd on his side.

Deprecate suppressFurntiture field froms Flags.

---

build.sbt
js/main.js
package.json
project/plugins.sbt
thrift/src/main/thrift/atoms/review.thrift

This provides a separation of the review atom and the actual thing being reviewed. The thing being reviewed is now modelled and exists within the content-entity library. Some SBT hackery was required when doing the thrift-js gen. @paulmr thanks for your help.
This PR also updates `scrooge-core` from `3.17.0` to `4.5.0`.

Introduce content-entity library to content-atoms

---

build.sbt

[For `year` type change](https://github.com/guardian/content-entity/pull/3)

Bump content-entity to 0.1.2

---

build.sbt

Makes `genre` field a list - https://github.com/guardian/content-entity/pull/4

Bump content-entity to 0.1.3

---

build.sbt
project/build.properties
thrift/src/main/thrift/atoms/recipe.thrift

- Add ingredients and image assets 
- [`quantity` is now optional](https://github.com/guardian/content-api/pull/1791) and new `optional` `quantityRange` field has been added.
- `images` is a required list 
Please some fields have been reordered because no recipes have yet been published
Apart from that I have done some health upgrade:
- `sbt` to `0.13.13`
- scala to `2.12.1`
- fix warnings from `sbt` `0.12` [upgrade](http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html)

Recipe add ingredients and image  assets

---

js/main.js
package.json
thrift/src/main/thrift/atoms/storyquestions.thrift
thrift/src/main/thrift/contentatom.thrift

A story question is a question, proposed by editorial or a user for a particular story. These questions will be presented in articles and pertain to the given story and present users with the ability to upvote them. This data will be sent to Ophan and dashboards will be built off of the back of it. These dashboards will aid journalistic intent, by allowing content to be commissioned (in some form) based of the direct feedback of our readers. 
See: https://docs.google.com/document/d/1fnQorQ7P9XHkha48BDwo6_f2nv-bPE-J1dcJO0ZOgF0/edit#

Content Atom - Adding 'story questions' atom.

---

thrift/src/main/thrift/contentatom.thrift

Everywhere else (including in the `AtomType` enum) this is called `qanda`. This will make things simpler in capi.

Rename qa -> qanda

---

thrift/src/main/thrift/atoms/storyquestions.thrift
thrift/src/main/thrift/shared.thrift

After discussion, this is going to be a permanent feature so it makes sense to add this field to the storyquestions atom itself.

Add an optional field to store the ID of an Exact Target subscriber list

---

thrift/src/main/thrift/atoms/storyquestions.thrift

Currently Editorial remove the atom from content when they want to close the questions.
It's preferable to leave the atom on the content, with the ability to hide it later.

Storyquestions 'closed' flag

---

thrift/src/main/thrift/atoms/media.thrift
thrift/src/main/thrift/shared.thrift

Add new fields to media atom to allow for adding composer trail images in mam. 
Composer trail image is saved in trail image field. The image model needs new fields because composer requires more information from the grid.

add trail image to media atom

---

build.sbt
project/plugins.sbt

Both are used in the atom rendering lib

Bump thrift-scrooge version to match fezziwig's

---

thrift/src/main/thrift/atoms/storyquestions.thrift

We would like to have the ability to track answers of questions in multiple forms (content, atom, etc..). We currently have the ability to do it for a set of questions but this is too general. I have define `answers` as a collection in case someone would like to commission multiple pieces for a given question. I am not expecting to be canonical but having the ability allows us to be `future proof`
This feature will be used for both:
- Tracking in `ophan` commissioned responses to a given question
- Automate sending emails when a response has been commissioned.

Add the ability to multiple answers 

---

thrift/src/main/thrift/contentatom.thrift

This adds a field an embargo field to the model.
NB: changes to the ES mapping are required, as this field will need to appear in CAPI

Add embargo date field for atoms

---

version.sbt

This is required to fix a failed deploy of the previous' version artifact on sonatype

Skip to version 2.4.57-SNAPSHOT

---

thrift/src/main/thrift/contentatom.thrift

Adds an expiryDate field at the `ContentChangeDetails` level. This is part of the work to make it possible to filter atoms on CAPI by date range

Add expiryDate field

---

thrift/src/main/thrift/contentatom.thrift

Adds an expiry field at the ContentChangeDetails level. This is part of the work to make it possible to filter atoms on CAPI by date range. Deprecate wrong expiryDate field

add expiry field, deprecate expiryDate field

---

thrift/src/main/thrift/atoms/commonsdivision.thrift
thrift/src/main/thrift/contentatom.thrift

I considered using the content-entity library to model the MPs, but decided against it. It would involve creating the entities in capi and linking to them with entityIds. We can add an optional Person entity field later if we decide it's useful to have that relationship.

Commons division atom

---

thrift/src/main/thrift/shared.thrift

We want to add 4 new fields to images within atoms:
1. source
2. copyright
3. photographer
4. suppliersReference
[Related ElasticSearch Mapping Change](https://github.com/guardian/content-api/pull/2085) 
[Trello ticket](https://trello.com/c/GexFvYIf/240-add-new-fields-for-atom-images-adding-fields-for-atom-images-copyright-source-photograph-so-rcs-can-better-process-rights)

Add 4 new properties on image

---

thrift/src/main/thrift/atoms/media.thrift
thrift/src/main/thrift/shared.thrift

We also need to save the suppliers reference and the photographer fields with the trail images that are included in composer video pages. These fields do not have to appear in capi.

add new image fields

---

thrift/src/main/thrift/atoms/media.thrift
thrift/src/main/thrift/shared.thrift

Reverts guardian/content-atom#104
These fields did not make it into CAPI since they're not used anywhere, so it's safe to revert. I'll release capi-models as soon as this is out.

Revert "add new image fields"

---

thrift/src/main/thrift/atoms/media.thrift

this is to allow rendering clients to distinguish a live stream from a normal video

add livestream as a category for media atoms

---

build.sbt

This library is pulling in v0.9.3 of libthrift despite downstream libraries overriding it, which seems to have broken client applications like frontend and MAPI when the Thrift model is updated.
I've tested this by updating all downstream dependencies and using in frontend with both the PROD and CODE versions of concierge (the former using an older model, the latter the latest one), to confirm this is working in both cases.
Addendum: to be fair, I noticed the facia client was using an old version of the CAPI model and this may be another source of incompatibility. I will update the docs so that, every time we update the model, we make sure all downstream libraries are updated too.

Enforce libthrift 0.9.1

---

thrift/src/main/thrift/atoms/media.thrift

This is to enable https://github.com/guardian/media-atom-maker/pull/848.

youtube specific title and description

---

build.sbt
project/build.properties
project/plugins.sbt

Upgrade to scrooge 19.3

---

thrift/src/main/thrift/atoms/chart.thrift

Adds values to the `ChartType` enum used by the existing `ChartAtom` type. This will allow the chart tool to save line charts in CAPI.
I don't believe it's necessary to amend the [elasticsearch mappings](https://github.com/guardian/content-api/blob/master/elasticsearch/es-config/templates/atoms-mapping.json#L239) in this case, as the overall structure of the atom has not changed.

ChartAtom: add new ChartType values

---

README.md

According to research and the CAPI team this NPM module is not being used. Therefore we are removing these confusing instructions from the READ.me. 
The package should also be removed at some point.

Update readme - npm package no longer used

---

thrift/src/main/thrift/atoms/emailsignup.thrift
thrift/src/main/thrift/contentatom.thrift

This should support an atom type for Editorial email sign up boxes, currently included as html snippets like this:
```
<figure class="element element-embed" data-alt="Business email signup">
<iframe src="https://www.theguardian.com/email/form/plaintone/3887" height="42px" data-form-title="Sign up for Business Today" data-form-description="Get the headlines and editors' picks every weekday morning." scrolling="no" seamless="" frameborder="0" class="iframed--overflow-hidden email-sub__iframe js-email-sub__iframe js-email-sub__iframe--article" data-form-success-desc="Thanks for signing up" data-node-uid="2"></iframe>
<figcaption class="caption caption--img">
Sign up to the daily Business Today email or follow Guardian Business on Twitter at @BusinessDesk
</figcaption>
</figure>
```
This is …

WIP: Add emailsignup atom

---

build.sbt
project/plugins.sbt

It now publishes `.d.ts` files alongside the compiled `.js` files, rather than `.ts` and `.js` as it was initially set up.
This ensures the client project that consumes the NPM package doesn't get any compilation error coming from the generated library.

Upgrade the typescript generation plugin.

---

.gitignore
README.md
build.sbt
project/plugins.sbt
thrift/src/main/thrift/atoms/recipe.thrift
version.sbt

We're bumping scrooge and thrift dependencies, which in turn meant we had to update our content-entity dependency too. We are similarly updating the sbt-scrooge-typescript sbt plugin (which is managed by us) and the scrooge-sbt-plugin which is provided by Twitter.
The update to scrooge brought with it an enforced reserved word check on field names, so we're aiming to update the affected fields in as painless and obvious way as possible.
Guidance received suggests that renaming fields is acceptable since it is the IDs of the fields that are critical to maintain compatibility, but we would expect compilation errors to trap any use cases where this isn't true. The overall shape of the data remains unchanged however.
We enabled construction of beta builds and using this branch released; …

Upgrade dependencies and enable beta builds

---

thrift/src/main/thrift/atoms/media.thrift

Support the new `youtubeOverrideImage` for media atoms. This looks the existing image fields, but will allow users to specify an image to send to YouTube and use as a thumbnail.
Related PRs:
- https://github.com/guardian/content-api/pull/2721
- https://github.com/guardian/media-atom-maker/pull/1077

Add youtubeOverrideImage to thrift definition

---

thrift/src/main/thrift/atoms/audio.thrift

As part of the work to add pocketCastsUrl to CAPI, the MSS team added this field to Porter (https://github.com/guardian/content-api/pull/2751), but the field also needs to be added to the audio.thrift so it could be referenced in `ContentAtomTestData.scala.`

Add pocketCastsUrl field to audio

---

README.md
build.sbt
package.json
version.sbt

Chasing down some Snyk complaints related to Thrift < 0.11.0.
This appears to have happened because `package.json` had been neglected during the last update(s).
Have brought this project's own version number in line with `build.sbt` and have added some notes to help keep things aligned in future.

Bump thrift dependency

---

thrift/src/main/thrift/atoms/recipe.thrift

As sketched out with Michel. Part of an ongoing effort to get recipe structured data rendering automatically on any recipe article with a recipe atom on it. 
The goal with this PR is for recipe atoms to have enough detail that they can be used to generate [recipe schema](https://schema.org/Recipe) when rendering pages. Getting to a viable bare minimum requires the following changes:
- More granular step details - title, text, image, and link
Also, with one eye on the work done by Data Tech we've also included nutritional information. It's not needed for bare minimum schema but may well be handy to have further down the line.
- Will this automatically translate to the Atom Workshop input UI updating?

Flesh out recipe thrift model

---

package.json

We're about to release this - just had to nudge the version in `package.json` first.

Resync package.json version with expected next release 3.4.4

---

.github/workflows/release.yml
README.md
build.sbt
project/build.properties
project/plugins.sbt

Following the example of `content-api-firehose-client' attempt to release via GitHub actions.
Regression of Beta releases while trying to work this out =(

Release via GitHub actions

---

.github/workflows/ci.yml

Before adopting gha-scala-workflow release process we need to put CI. 
As of now we are going ahead with only `sbt compile` action in it. 
`sbt test` will be added after we add some tests (We will put "add testcases" work in health tasks for us).

Add CI to the project

---

.github/workflows/release.yml
README.md
build.sbt
project/build.properties
project/plugins.sbt

**Changes**
Implementing `gha-scala-release-workflow` process ref: https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/configuration.md
to have release process with organisation based secrets, more secured, less code for maintainability, easy to deploy on both maven and npm.
Since it requires release on npm as well. We have taken npm release changes from content-api-models ref:https://github.com/guardian/content-api-models/blob/main/.github/workflows/release.yml

Adopt gha-scala-rel-workflow in the project

---

build.sbt

We have got latest release of `content-entity` after implementing `gha-scala-library-release`
This PR will bump that version and test as well.

Bump content-entity's latest release

---

build.sbt

This will ensure compatibilty check by the release process

Add version compatability check

---

build.sbt
package-lock.json
package.json

No model changes; simply bumps Thrift Node library to current latest 0.20.0 (Apr 2024)

Update thrift library

---

.github/workflows/ci.yml
.github/workflows/release.yml

Adds `setup-sbt` to workflow
Note that `setup-scala` was not used due to a discrepancy between the `java-version` in `setup-java` and that in the pre-existing `.tool-versions` file
Workflow ran successfully on this branch
No failing workflows when Github takes sbt away from us!

Add setup-sbt to workflow
