guardian/content-atom

src/main/thrift/atoms/quiz.thrift

Adds the revealAtEnd field to the content atom
\cc @paulmr

Add the reveal at end type

---

src/main/thrift/atoms/quiz.thrift

Not sure if this is how we want to represent these
\cc @paulmr @chrisfinch

Add result buckets to the quz content atom

---

src/main/thrift/atoms/quiz.thrift

from the result groups.
\cc @paulmr

Remove the reveal at end that I forgot to remove

---

src/main/thrift/atoms/quiz.thrift

Reverts guardian/content-atom#10

Revert "Add optional publishedAt field to Quiz thrift definition"

---

package.json
version.sbt

Merging viewports and media breaking changes

bump to v2

---

README.md
js/main.js
package.json
version.sbt

Didn't realise this was a manual step.

add media types to main

---

thrift/src/main/thrift/atoms/explainer.thrift
thrift/src/main/thrift/contentatom.thrift

For the explainer atom editor. There will likely be more fields to follow.

Add explainer atom type.

---

thrift/src/main/thrift/atoms/explainer.thrift

I missed this off when initially creating the atom.

Add scala namespace for explainer atom.

---

thrift/src/main/thrift/atoms/cta.thrift
thrift/src/main/thrift/contentatom.thrift

Adds a thrift model for call to action atom.

thrift model for cta atoms

---

thrift/src/main/thrift/atoms/interactive.thrift
thrift/src/main/thrift/contentatom.thrift

Adds an interactive atom definition, see https://github.com/guardian/content-api/pull/1721 for details

Interactive atom definition

---

thrift/src/main/thrift/atoms/media.thrift

This PR adds the metadata we want to send to YouTube. 
@clloyd

Adds media atom metadata

---

js/main.js
package.json
project/build.properties
thrift/src/main/thrift/atoms/recipe.thrift

See [elasticsearch mapping related change](https://github.com/guardian/content-api/pull/1737)

Add recipe atom

---

package.json
thrift/src/main/thrift/atoms/review.thrift

See: https://www.elastic.co/guide/en/elasticsearch/guide/current/lat-lon-formats.html for info.

Content atom - change review field lng to lon.

---

thrift/src/main/thrift/atoms/review.thrift

Game review type enum

---

package.json
thrift/src/main/thrift/atoms/media.thrift

models the three privacy states of a YouTube video

add privacyStatus field

---

README.md

Update for cross releasing

---

README.md

Correct sbt command in readme

---

README.md

add instructions for cross releasing locally

---

package.json
thrift/src/main/thrift/atoms/recipe.thrift

Companion PR: https://github.com/guardian/content-api/pull/1788

recipe model update: adding 'optional string unit' to Serves

---

thrift/src/main/thrift/contentatom.thrift

Add top level title and takenDown change record

---

package.json
thrift/src/main/thrift/contentatom.thrift

- Add a new flag to media atom.
@akash1810

Media atom usage policy

---

thrift/src/main/thrift/atoms/media.thrift
thrift/src/main/thrift/contentatom.thrift

Add video source, trail text and sensitive flag to media atom 
@akash1810 @mbarton

Add new media atom fields

---

thrift/src/main/thrift/atoms/media.thrift

adds more fields for Pluto, in its own `struct`.

more pluto fields

---

thrift/src/main/thrift/atoms/storyquestions.thrift

assumed this project triggers a build!

Fix closeDate

---

thrift/src/main/thrift/shared.thrift

aspect ratio belongs to ImageAsset

add aspect ratio to image

---

thrift/src/main/thrift/atoms/media.thrift

the structure of the media atom isn't very intuitive, its too late to change the structure so add some comments for clarity

add comments to media properties

---

thrift/src/main/thrift/atoms/media.thrift

add:
- optimised for web
- comments enabled
- suppress related content
also adds comments for some fields

the last of the Composer fields

---

thrift/src/main/thrift/atoms/timeline.thrift

Associated relevant PRs for change that have been merged:

Snippets [Timeline] - Allow flexible date formatting  

---

thrift/src/main/thrift/atoms/chart.thrift
thrift/src/main/thrift/contentatom.thrift

🗣  NEW ATOM TYPE ⚛️
Add the chart atom type to model... charts. This is part of the effort to make working with https://visuals.gutools.co.uk/basichartool/ a bit easier.

chart atom structure

---

README.md
thrift/src/main/thrift/atoms/chart.thrift

Add scala namespace and update readme.

---

.github/PULL_REQUEST_TEMPLATE.md

Add warning about scala namespacing.

---

thrift/src/main/thrift/atoms/chart.thrift

Following the addition of Line charts, we want to add the rest of the charts so that we can simply run the series of updates one. 
These are all the chart types requested by the visuals team for the end of the quarter.

CHART TYPES: add more chart types

---

thrift/src/main/thrift/atoms/interactive.thrift

See in-line comment for why this field is being added.

New placeholder field for interactives

---

project/build.properties

Bump sbt version to 1.5.7
